



type Mutation {
	createOrganization(
		"""
		name of object
		"""
		name: String!,
		"""
		organization_type of object
		"""
		organizationType: String!,
		"""
		private_key of object
		"""
		privateKey: String
	): OrganizationSchema!
}

type OrganizationSchema {
	id: String!
	name: String!
	organizationType: OrganizationType!
}

enum OrganizationType {
	PUBLIC
	PRIVATE
}

type Query {
	currentToken: String
	findOne(
		"""
		id of object
		"""
		id: ID!
	): OrganizationSchema!
}


schema {
	query: Query
	mutation: Mutation
}
