



type ItemSchema {
	id: String!
	name: String!
	organizationId: String!
}

type Mutation {
	createOrganization(
		"""
		name of object
		"""
		name: String!,
		"""
		organization_type of object
		"""
		organizationType: String!,
		"""
		private_key of object
		"""
		privateKey: String
	): OrganizationSchema!
	createItem(
		"""
		item name
		"""
		name: String!,
		"""
		item organization_id
		"""
		organizationId: String!
	): ItemSchema!
}

type OrganizationSchema {
	id: String!
	name: String!
	organizationType: OrganizationType!
}

enum OrganizationType {
	PUBLIC
	PRIVATE
}

type Query {
	currentToken: String
	organizationFindOne(
		"""
		id of object
		"""
		id: ID!
	): OrganizationSchema!
}


schema {
	query: Query
	mutation: Mutation
}
